config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'about', to: 'pages#about'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    validates :title, presence: true, length: {minimum: 10, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    def index
        @articles = Article.all
    end

    def show

    end

    def new
        @article = Article.new
    end    
    
    def edit

    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article successfully created"
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article successfully updated"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        
    end

    def about
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_errors.html.erb
<% if @article.errors.any? %>
<h2>The following errors need to be addressed</h2>
    <ul>
        <% @article.errors.full_messages.each do |message|%>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
    <p> 
        <%= form.label :title %>
        <%= form.text_field :title %>
    </p>
    <p> 
        <%= form.label :description %>
        <%= form.text_area :description %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article Page</h1>

<%= render 'errors' %>
<%= render 'form' %>

<p><%= link_to "Cancel", articles_path %></p>

app/views/articles/index.html.erb
<h1>Articles index</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to "View", article_path(article) %></td>
            <td><%= link_to "Edit", edit_article_path(article) %></td>
            <td><%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?"} %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<p><%= link_to "Create New Article", new_article_path %></p>

app/views/articles/new.html.erb
<h1>New Articles Page</h1>

<%= render 'errors' %>
<%= render 'form' %>

<p><%= link_to "All Articles", articles_path %></p>

app/views/articles/show.html.erb
<h1>This is the articles show page</h1>
<h2><%= @article.title %></h2>
<p><%= @article.description %></p>

<p><%= link_to "Edit", edit_article_path(@article) %></p>
<p><%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?"} %></p>
<p><%= link_to "All Articles", articles_path %></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

<p><%= link_to "Articles Listing", articles_path %></p>
<p><%= link_to "About", about_path %></p>